\c mary
INSERT INTO year
    (year)
VALUES
    ('40'),
    ('1061')
    ('1251')
    ('1490')
    ('1531')
    ('1570, 1597')
    ('1608')
    ('1798')
    ('1830')
    ('1842')
    ('1846')
    ('1858')
    ('1859')
    ('1871')
    ('1876')
    ('1877')
    ('1879')
    ('1900')
    ('1917')
    ('1932-1933')
    ('1933')
    ('1945')
    ('1947')
    ('1948')
    ('1968')
    ('1973')
    ('1980')
    ('1981-Present')
    ('1981-1983')
    ('1982-1983')
    ('2000-2001')
INSERT INTO location
    (location)
VALUES
    ('Zaragoza, Spain')
    ('Walsingham, England')
    ('Aylesford, England')
    ('Monte Figogna, Italy')
    ('Mexico City, Mexico')
    ('Nadu, India')
    ('Siluva, Lithuania')
    ('Quang Tri, Vietnam')
    ('Paris, France')
    ('Rome, Italy')
    ('La Salette, France')
    ('Lourdes, France')
    ('Wisconsin, USA')
    ('Pontmain, France')
    ('Pellovoisin, France')
    ('Gietzwald, Poland')
    ('Knock, Ireland')
    ('Hebei, China')
    ('Fatima, Portugal')
    ('Beauraning, Belgium')
    ('Banneux, Belgium')
    ('New York, USA')
    ("L'lle-Bouchard, France")
    ('Batangas, Philippines')
    ('Cairo, Egypt')
    ('Akita, Japan')
    ('San Francisco de Cuapa')
    ('Medjugorje')('Bosnia-Herzegovnia')
    ('Kibeho, Rwanda')
    ('Damascus, Syria')
    ('Asyut, Egypt')

INSERT INTO witnesses
    (witnesses)
VALUES
    ('St. James the Apostle')
    ('Reicheldis de Faverches')
    ('St. Simon Stock')
    ('Benedetto Pareto')
    ('St. Juan Diego, Juan Bernardino')
    ('Tamil Krishnannesti Sankaranarayanan and an unknown boy')
    ('Several townspeople')
    ('Several townspeople')
    ('St Catherine Laboure')
    ('Marie-Alphonse Ratisbonne')
    ('Melanie Mathieu-Calvat, Maximim Giraud')
    ('St. Bernadette Soubirous')
    ('Adele Brise')
    ('Eugene & Joseph Barbadette, Jeanne-Marie Lebosse, Francoise Richer')
    ('Estelle Faguette')
    ('Stanislawa Samulowska, Justyna Szafrynska')
    ('15 townspeople')
    ('700 people')
    ('Lucia Santos, Jacinta Marto, Francis Marto, plus >70,000 who witnessed the miracle of the sun')
    ('Andreee Degeimbre, Gilgerte Degeimbre, Albert & Fernande & Gilberter Voisin')
    ('Mariette Beco')
    ('Joseph Vitolo')
    ('Jacqueline & Jeanette Aubry, Nicole Robin, Laura Croizon, Tersita Castillo')
    ('Estimated > 1,000,000 people, including President Abdel Nassar')
    ('Sr. Agnes Katsuko Sasagawa')
    ('Bernardo Martinez')
    ('Jakov Colo, Ivan & Mirjana Dragicevic, Marija Pavlovic, Ivanka & Vicka Ivankovic')
    ('Alphonsine Mumureke, Nathalie Mukamazimpaka, Marie Claire Mukangango')
    ('Mary Kourbet Nazzour')
    ('Thousands of people')
    


